### ISSUE TITLE
Lack of contrast

### ISSUE THREAD

**Issue by doomedramen** [jolaleye/cssfx#2]
Love the site and the idea, sadly a couple of the fx are not visible on my monitor (Apple display) such as "Pulse" due to there being such a low contrast between the buttons and the background, I would suggest lightening the buttons a little (happy to put in a PR).

**Comment by doomedramen** [comment]
Something like "#3a356f" works well for me.

**Comment by jolaleye** [comment]
Thanks for the feedback, Martin! I've updated the hover, button, and modal colors to help with the contrast issues. Check it out and let me know what you think :) This will likely need continued tuning.

**Comment by doomedramen** [comment]
Thanks for taking my input Jonathan,
Tested on 6 devices and looks great on 5 (the apple display still looks low contrast but much improved,  I'm putting that down to the particular display).
I look forward to using CSSFX in my future projects.
