### ISSUE TITLE
homepage shift/move when click

### ISSUE THREAD

**Issue by boban-dj** [jolaleye/cssfx#4]
add html `{ overflow-x:auto; overflow-y:scroll; }`
to your homepage to prevent movement page

**Comment by jolaleye** [comment]
I can't seem to reproduce unwanted movement. Could you provide more details, maybe a screenshot?

**Comment by boban-dj** [comment]
its not a big deal but you can see here https://vimeo.com/335314578

**Comment by jolaleye** [comment]
Hmm... I see what you mean, but I still can't reproduce the issue. I'll add the rule anyway though, it can't hurt.

**Comment by jolaleye** [comment]
Update is live, let me know if the issue persists.

**Comment by boban-dj** [comment]
Its fixed now, it was really not a big deal but annoying as your design is clean, it was visible in chromium Version 74.0.3729.131 and firefox 66.0.3 (64-bit)
