### ISSUE TITLE
Problems with Safari

### ISSUE THREAD

**Issue by liquidvisual** [jolaleye/cssfx#6]
First of all, awesome job - this is a great resource. Just a heads up; some of the effects don't render properly in Safari (mainly Bubble and Shine).

**Comment by jolaleye** [comment]
Thank you!
I'm aware of the bugs with Safari and I'll try to get around to fixing them soon. Thanks for reporting it and feel free to take a stab at a fix :)

**Comment by jolaleye** [comment]
Couple things I've discovered so far...

1. Other flicker-related issues on Safari seemed to be solved with `backface-visibility`, `translate3d`, or `transform-style`. These don't seem to work for the bubble effects yet though.
2. When I toggle the hover state in Safari dev tools, the shine effect works properly.

There seems to just be a mess of bugs in Safari and I haven't been able to find the style combination to fix them yet.

**Comment by jolaleye** [comment]
Bubble effects now work properly thanks to @zmj97. Shine effect is still having issues though.
